import Foundation
import SwiftUI

struct ScheduleView: View {
    @ObservedObject var session: SessionStore

    var body: some View {
        List {
            Section {
                if session.schedule.isEmpty {
                    Text("No schedule has been generated yet. Refresh Today after your first sign-in to ask Hermes for the next block.")
                        .font(HermesTheme.body)
                        .foregroundStyle(HermesTheme.mutedInk)
                        .padding(.vertical, 18)
                        .listRowBackground(HermesTheme.paperRaised)
                } else {
                    ForEach(Array(session.schedule.enumerated()), id: \.offset) { _, workout in
                        ScheduleRow(workout: workout)
                            .listRowBackground(HermesTheme.paperRaised)
                    }
                }
            } header: {
                HermesSectionLabel(text: "Next 14 days")
                    .textCase(nil)
            } footer: {
                Text("The schedule is generated by the same Coach API as Today Run. Native editing and training-block controls remain on the web route.")
            }
        }
        .scrollContentBackground(.hidden)
        .background(HermesTheme.paper.ignoresSafeArea())
        .navigationTitle("Schedule")
        .navigationBarTitleDisplayMode(.inline)
        .refreshable { await session.refreshDashboard() }
        .task { if session.dashboard == nil { await session.refreshDashboard() } }
    }
}

private struct ScheduleRow: View {
    let workout: HermesScheduledWorkout

    var body: some View {
        HStack(spacing: 14) {
            VStack(alignment: .leading, spacing: 5) {
                Text(dateLabel)
                    .font(HermesTheme.caption)
                    .foregroundStyle(HermesTheme.mutedInk)
                Text(title)
                    .font(.system(size: 16, weight: .bold, design: .rounded))
                    .foregroundStyle(HermesTheme.ink)
            }
            Spacer()
            VStack(alignment: .trailing, spacing: 5) {
                Text(HermesFormatters.distance(workout.plannedDistanceKm))
                    .font(.system(size: 16, weight: .bold, design: .rounded))
                    .foregroundStyle(HermesTheme.ink)
                Text(HermesFormatters.plannedTime(minutes: workout.plannedDurationMinutes))
                    .font(HermesTheme.caption)
                    .foregroundStyle(HermesTheme.mutedInk)
            }
        }
        .padding(.vertical, 8)
    }

    private var title: String {
        let value = workout.workoutType?.replacingOccurrences(of: "_", with: " ") ?? "Rest"
        return value.capitalized
    }

    private var dateLabel: String { HermesFormatters.date(HermesDate.parse(workout.scheduledDate)) }
}

struct ScheduleView_Previews: PreviewProvider {
    static var previews: some View {
        NavigationStack { ScheduleView(session: SessionStore(previewDashboard: HermesPreviewFixtures.dashboard)) }
    }
}
